# A generic, single database configuration for Alembic.

[alembic]
# path to migration script directory
script_location = alembic

# template used to generate migration file names; The default is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the file template
# and in log output.
timezone = UTC

# max length of characters which are used to render the
# string of the 'slug' in the file template
truncate_slug_length = 40

# output_encoding is the encoding used when version files are written
output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/mystic_security

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

# Logging configuration
[loggers]
keys = root, alembic, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
